"""Add account status

Revision ID: 7184714be38b
Revises: ceb387862674
Create Date: 2026-02-25 00:48:46.411271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlalchemy_utc
import sqlmodel.sql.sqltypes
from sqlmodel import Text
from appserver.apps.account.enums import AccountStatus


# revision identifiers, used by Alembic.
revision: str = '7184714be38b'
down_revision: Union[str, Sequence[str], None] = 'ceb387862674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(), nullable=False, server_default=AccountStatus.ACTIVE.value))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
