"""google_event_id

Revision ID: 78e0d09a8756
Revises: 7184714be38b
Create Date: 2026-03-04 17:48:10.139908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlalchemy_utc
import sqlmodel.sql.sqltypes
from sqlmodel import Text


# revision identifiers, used by Alembic.
revision: str = '78e0d09a8756'
down_revision: Union[str, Sequence[str], None] = '7184714be38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('google_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'google_event_id')
    # ### end Alembic commands ###
