"""bookingfile model

Revision ID: ceb387862674
Revises: bf8351584432
Create Date: 2026-02-23 17:09:29.383368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlalchemy_utc
import sqlmodel.sql.sqltypes
from sqlmodel import Text

import fastapi_storages.integrations.sqlalchemy
from fastapi_storages import FileSystemStorage


# revision identifiers, used by Alembic.
revision: str = 'ceb387862674'
down_revision: Union[str, Sequence[str], None] = 'bf8351584432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    # sa.Column('file', fastapi_storages.integrations.sqlalchemy.FileType(), nullable=False),
    sa.Column('file', fastapi_storages.integrations.sqlalchemy.FileType(storage=FileSystemStorage(path="uploads/bookings")), nullable=False),
    # sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='fk_booking_files_booking_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bookings', sa.Column('attendance_status', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), nullable=False))
    op.drop_column('users', 'hashed_password')
    op.drop_column('bookings', 'attendance_status')
    op.drop_table('booking_files')
    # ### end Alembic commands ###
